### ISSUE TITLE
`use_rmdgh`?

### ISSUE THREAD

**Issue by Robinlovelace** [MilesMcBain/issuecreep#20]
Hi Miles, love the idea! 

It reminds me of https://github.com/mattduck/gh2md but this is a whole lot more powerful, and focusses on writing issues (rather than saving them to read in contexts without internet access).

My first question when using gh2md was 'where do I put stuff' and the same question applies here. Worth considering a `use_rmdgh` function to

- [ ] Create a folder for saving and editing issues, e.g. `issues`
- [ ] Adding that to the buildignore
- [ ] Anything else...

**Comment by MilesMcBain** [comment]
Thanks @Robinlovelace!

I mostly imagined the issue Rmd’s would be ephemeral. This is why there’s so
much tooling to aid finding and getting to an issue thread quickly. Similarly
with issues you’re creating, once you’ve submitted it to GitHub, I didn’t
imagine there’d be much point in keeping the source around, unless it’s a big and
complex one and you have to work on it in a few sessions.

At the moment this is where things stand:

-   Rmd’s for issues you open via `jump_to_issue_thread` or `gh_thread` are
    created in the `tools::R_user_dir("rmdgh")` folder and automatically deleted in
    the future.  
-   When calling `draft_issue()` you have the option to create the issue in the
    `R_user_dir` folder or the current working directory. Controlled by the
    `tempdir = getOption("draft_issue_in_tempdir", TRUE)`

The setup for `draft_issue()` is a bit weird. It would be more common to see
a path argument for this. That’s easy to add if it would help. Perhaps
also defaulting from an option or env var so that you can set it via project
level file config.

I am not sure if creating issue Rmd’s for threads you’re jumping to in the local
directory is desirable. You could accumulate a lot of documents very fast with
this and I wouldn’t want to automatically clean up anything in user space.

Perhaps I need to understand a bit more about your workflow. What kinds of
things do you want to stash in the current project? And do you want that to always
happen, or do you want to be able to do that easily if you choose to?

One thing that might be cool is a `issue_save_as()` command that copies the
current Rmd to somewhere in your current working directory.

**Comment by Robinlovelace** [comment]
> Perhaps I need to understand a bit more about your workflow. What kinds of
> things do you want to stash in the current project? And do you want that to always
> happen, or do you want to be able to do that easily if you choose to?

Well it's just handy to have a copy of issues in the repo sometimes, but maybe that's a bit of a niche use case. What I'm thinking is that there's an issue created with a .Rmd file and someone wants to quickly reproduce it, could be handy to have the source code in an issues, or maybe `data-raw/issues` folder, right?

One point, the formatting of your comment above is a bit odd, is that due to rmdgh? May want the output to be paragraph-based breaks if so.

**Comment by MilesMcBain** [comment]
> One point, the formatting of your comment above is a bit odd, is that due to rmdgh? May want the output to be paragraph-based breaks if so.

No and Yes. I have a habit of hitting the reflow shortcut in Vim mode which aligns everything to 80 chars. Normally the knitting process would join these lines by default, but I switched the default to leave them alone. It looked good on my monitor, but horrible when I looked at this issue on my mobile. So I think I’ll switch the default back.

> What I’m thinking is that there’s an issue created with a .Rmd file and someone wants to quickly reproduce it, could be handy to have the source code in an issues, or maybe `data-raw/issues` folder, right?

Yes. The problem is that search results can return issues for many repos, which you could navigate, to materialising them into Rmd documents. Should I put all Rmd’s you open into `data-raw/issues` even if they’re not from the current repo? I want to encourage browsing quickly and freely without having to worry about accumulating documents you may need to delete later. This makes me think the best option might be some kind of `save_issue()` function which stores them in a configurable sub folder of the current working directory.

**Comment by Robinlovelace** [comment]
> This makes me think the best option might be some kind of `save_issue()` function which stores them in a configurable sub folder of the current working directory.

:+1: to that

**Comment by MilesMcBain** [comment]
Done! `save_issue()` has a configurable folder that is automatically
created and added to \`.Rbuildignore’

**Comment by Robinlovelace** [comment]
Amazing, many thanks Miles!
